### ISSUE TITLE
Brainstorm participant goals for intro workshop

### ISSUE THREAD

**Issue by jadrian** [CfABrigadePhiladelphia/decentralized-data#12]
A fair bit of time in the intro workshop is going to be devoted to "getting-to-know-you" stuff.  How can the workshop leader act, and what questions can they ask, to best frame the workshop for an outcome that serves our intentions?

Participants should come away understanding:
- That everyone (including the leader) has their own goals, knowledge gaps, worries, skills, unique perspective, and a unique communication style
- The nature of each other's goals, skills, etc.
- That we will succeed as a team when we're all open about what we know and don't know
- How to get help and report problems during workshops and between workshops

... what else?

**Comment by flyingzumwalt** [comment]
Related: use this session to make sure everyone is on slack and github and gather the list of everyone's handles.

**Comment by kailok** [comment]
I am not sure I fully understand what at this point I should have understood as a participant.  I also worry my skill set isn't enough to help, but I want to state that the most important criterion may have been met anyway.  (or close enough).  I'm really looking forward to Tuesday.  I'm willing to throw all sorts of free time at it, and for me, that's not nothing.
