### ISSUE TITLE
nonexistent or nonpublic link

### ISSUE THREAD

**Issue by maneesha** [CfABrigadePhiladelphia/decentralized-data#14]
At bottom of this page:

https://codeforphilly.github.io/decentralized-data/tutorials/actually-using-git/lessons/conflicting-branches/

returns 404, meaning it's either a nonexistent or nonpublic link.

**Comment by flyingzumwalt** [comment]
What is the url that returns a 404?

**Comment by komaron** [comment]
https://github.com/CodeForPhilly/decentralized-data-examples

**Comment by flyingzumwalt** [comment]
Fixed it. @maneesha was right. I had accidentally made the repo private.
