### ISSUE TITLE
Post calendar of workshops on datjawn project page

### ISSUE THREAD

**Issue by flyingzumwalt** [CfABrigadePhiladelphia/decentralized-data#9]
Post the calendar of workshops on the [datjawn Code for Philly page](http://datjawn.com)

this is blocked by #8
## Announcement (WIP)

| Week | Date | Location | Topic (and links to workshops) |
| --- | --- | --- | --- |
| 1 | 10/04/2016 | TBD | [Introduction](https://codeforphilly.github.io/decentralized-data/tutorials/): Project overview, roadmap, and technical fundamentals |
| 2 | 10/11/2016 | TBD | [Get Started with Golang](https://codeforphilly.github.io/decentralized-data/tutorials/get-started-with-golang) |
| 3 | 10/18/2016 | TBD | Version Control Week I: [Git hands-on & light theory](https://codeforphilly.github.io/decentralized-data/tutorials/git-basics) |
| 4 | 10/25/2016 | TBD | Version Control Week II: [Pull Requests and Code Reviews](https://codeforphilly.github.io/decentralized-data/tutorials/code-reviews) |
| 5 | 11/01/2016 | TBD | Version Control Week III: [Noms hands-on](https://codeforphilly.github.io/decentralized-data/tutorials/noms) |
| 6 | 11/08/2016 | TBD | Version Control Week IV: Panel discussion — what do our users want to do with their data?  How could Noms (and Noms+IPFS) help? |
| 7 | 11/15/2016 | TBD | Version Control Week V: [Under the Hood of Git and Noms](https://codeforphilly.github.io/decentralized-data/tutorials/git-noms-data-models): deeper theory / data models of Git and Noms |
| 8 | 11/22/2016 | TBD | [IPFS: hands-on & theory](https://codeforphilly.github.io/decentralized-data/tutorials/ipfs) |
| - | - | - | _Switch to Coding:_ The IPFS workshop will be the final “pre-development” workshop. The following workshops will be our “transition to development” phase, during which participants will need to decide whether they’ll participate in the sprints going forward. |
| 9 | 11/29/2016 | TBD | [Agile Process](https://codeforphilly.github.io/decentralized-data/tutorials/agile-process) Crash course in Agile Development Process / Methodology |
| 10 | 12/06/2016 | TBD | [Testing Your Code](https://codeforphilly.github.io/decentralized-data/tutorials/testing-code) Writing Tests, Running them, and Using Continuous Integration |

After this, we'll do eight weeks of development sprints, during which we'll design, build, test, and deploy our Noms–IPFS connector.

**Comment by flyingzumwalt** [comment]
I've posted it in the [readme](https://codeforphilly.org/projects/dat_tables). Waiting for chris to fix the CSS on the codeforphilly site so the table renders properly before announcing the link.

**Comment by themightychris** [comment]
@flyingzumwalt all set: CodeForPhilly/laddr@634307c8ee74cc9ec236de5683bf7ec8b5f07b28

**Comment by flyingzumwalt** [comment]
Ooh. It looks so nice! Thanks @themightychris
